apiVersion: v1
kind: Service
metadata:
  name: {{ include "adguard_sync.fullname" . | nindent 4 }}
  labels: {{ include "adguard_sync.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "adguard_sync.selectorLabels" . | nindent 4}}
